SHOW DATABASES;
CREATE DATABASE DATA2;
USE DATA2;
SHOW TABLES;
CREATE TABLE STUDENTS1(ID INT PRIMARY KEY,FULLNAME VARCHAR(50),LASTNAME VARCHAR(50),DATEOFBIRTH DATE,GRADE INT);
DESC STUDENTS1;
ALTER TABLE STUDENTS1
ADD EMAIL VARCHAR(100);
ALTER TABLE STUDENTS1 DROP COLUMN GRADE;
CREATE TABLE COURSE(COURSEID INT,COURSENAME VARCHAR(100) NOT NULL,CREDITS INT);
DESC COURSE;
INSERT INTO STUDENTS1 VALUES(1,"JOHN"," NOT NULLDOE","2005-04-12","JOHN.DOE@GMAIL.COM");
INSERT INTO STUDENTS1 VALUES(2,"JANE","SMITH","2004-08-21","JANE.SMITH@GMAIL.COM");
SELECT *FROM STUDENTS1;
UPDATE STUDENTS1 SET EMAIL="JOHN.NEWEMAIL@GMAIL.COM" WHERE ID=1;
DELETE FROM STUDENTS1 WHERE ID=1;
INSERT INTO COURSE VALUES(101,"MATHS",4),(102,"SCIENCE",3);
SELECT *FROM COURSE;
SELECT * FROM COURSE WHERE COURSENAME="MATHS";
ALTER TABLE COURSE ADD PRIMARY KEY (COURSEID);
DELETE FROM COURSE WHERE COURSEID = 101;
TRUNCATE COURSE;


